# Flatnet Nebula Host Node Setup Script
# Phase 3 - Stage 2
#
# Usage:
#   .\setup-host.ps1 -HostName host-a -LighthouseAddr "192.168.1.10:4242"
#   .\setup-host.ps1 -HostName host-b -LighthouseAddr "192.168.1.10:4242" -Install -Start -SetupFirewall
#
# Prerequisites:
#   - nebula.exe が F:\flatnet\nebula\ に配置されていること
#   - ホスト証明書が F:\flatnet\config\nebula\ に配置されていること
#     (host.crt, host.key, ca.crt)
#   - 管理者権限で実行 (-Install, -SetupFirewall オプション使用時)
#
# 証明書の配置:
#   Lighthouse ホストで証明書を生成後、以下のファイルを対象ホストにコピー:
#     - ca.crt           -> F:\flatnet\config\nebula\ca.crt
#     - <hostname>.crt   -> F:\flatnet\config\nebula\host.crt
#     - <hostname>.key   -> F:\flatnet\config\nebula\host.key

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]$HostName,

    [Parameter(Mandatory=$true)]
    [string]$LighthouseAddr,  # 例: "192.168.1.10:4242"

    [string]$LighthouseIp = "10.100.0.1",
    [int]$Port = 4242,
    [switch]$Install,
    [switch]$Start,
    [switch]$SetupFirewall,
    [switch]$SetupRouting,
    [string]$FlatnetBase = "F:\flatnet"
)

$ErrorActionPreference = "Stop"

# 管理者権限チェック関数
function Test-Administrator {
    $currentPrincipal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
    return $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

# パス設定
$Nebula = "$FlatnetBase\nebula\nebula.exe"
$NssmPath = "$FlatnetBase\nssm.exe"
$ConfigNebulaDir = "$FlatnetBase\config\nebula"
$LogsDir = "$FlatnetBase\logs"
$ConfigFile = "$ConfigNebulaDir\config.yaml"

$CaCrt = "$ConfigNebulaDir\ca.crt"
$HostCrt = "$ConfigNebulaDir\host.crt"
$HostKey = "$ConfigNebulaDir\host.key"

Write-Host "Flatnet Nebula Host Node Setup" -ForegroundColor Cyan
Write-Host "===============================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Host: $HostName"
Write-Host "Lighthouse: $LighthouseAddr (Nebula IP: $LighthouseIp)"
Write-Host ""

# nebula.exe の存在確認
if (-not (Test-Path $Nebula)) {
    Write-Error @"
nebula.exe が見つかりません: $Nebula

以下の手順で Nebula バイナリを取得してください:
1. https://github.com/slackhq/nebula/releases から nebula-windows-amd64.zip をダウンロード
2. 展開して nebula.exe と nebula-cert.exe を $FlatnetBase\nebula\ に配置
"@
    exit 1
}

# 証明書の存在確認
$missingFiles = @()
if (-not (Test-Path $CaCrt)) { $missingFiles += "CA 証明書: $CaCrt" }
if (-not (Test-Path $HostCrt)) { $missingFiles += "ホスト証明書: $HostCrt" }
if (-not (Test-Path $HostKey)) { $missingFiles += "ホスト秘密鍵: $HostKey" }

if ($missingFiles.Count -gt 0) {
    Write-Error @"
必要なファイルが見つかりません:
$($missingFiles -join "`n")

Lighthouse ホストで証明書を生成し、以下のファイルをこのホストにコピーしてください:
  - ca.crt           -> $CaCrt
  - <hostname>.crt   -> $HostCrt
  - <hostname>.key   -> $HostKey
"@
    exit 1
}

# logs ディレクトリ作成
if (-not (Test-Path $LogsDir)) {
    New-Item -ItemType Directory -Path $LogsDir -Force | Out-Null
}

# 設定ファイルの生成
Write-Host "設定ファイルを生成しています..."

# パス区切りをスラッシュに変換（YAML 用）
$FlatnetBaseYaml = $FlatnetBase -replace '\\', '/'

$configContent = @"
# Flatnet Nebula Host Node Configuration
# Generated by setup-host.ps1 at $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
# Host: $HostName

pki:
  ca: $FlatnetBaseYaml/config/nebula/ca.crt
  cert: $FlatnetBaseYaml/config/nebula/host.crt
  key: $FlatnetBaseYaml/config/nebula/host.key

# Lighthouse への接続設定
static_host_map:
  "$LighthouseIp": ["$LighthouseAddr"]

lighthouse:
  am_lighthouse: false
  hosts:
    - "$LighthouseIp"

listen:
  host: 0.0.0.0
  port: $Port

logging:
  level: info
  format: text

# TUN デバイス設定
tun:
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false

# ファイアウォール設定
firewall:
  # アウトバウンド: 全て許可
  outbound:
    - port: any
      proto: any
      host: any

  # インバウンド
  inbound:
    # ICMP (ping) を許可
    - port: any
      proto: icmp
      host: any
    # 同じグループからの通信を許可
    - port: any
      proto: any
      group: flatnet
    # Gateway グループからの通信を許可
    - port: any
      proto: any
      group: gateway
"@

Set-Content -Path $ConfigFile -Value $configContent -Encoding UTF8
Write-Host "  設定ファイル: $ConfigFile" -ForegroundColor Green

# 設定テスト
Write-Host ""
Write-Host "設定をテストしています..."
& $Nebula -config $ConfigFile -test
if ($LASTEXITCODE -ne 0) {
    Write-Error "設定テストに失敗しました"
    exit 1
}
Write-Host "  設定テスト: 成功" -ForegroundColor Green

# ファイアウォール設定
if ($SetupFirewall) {
    Write-Host ""
    Write-Host "ファイアウォールを設定しています..."

    if (-not (Test-Administrator)) {
        Write-Warning "ファイアウォール設定には管理者権限が必要です。管理者として再実行してください。"
    } else {
        # 既存ルールを削除
        $existingRules = Get-NetFirewallRule -DisplayName "Nebula*" -ErrorAction SilentlyContinue
        if ($existingRules) {
            $existingRules | Remove-NetFirewallRule -ErrorAction SilentlyContinue
        }

        # UDP ポート開放
        New-NetFirewallRule -DisplayName "Nebula UDP" -Direction Inbound -Protocol UDP -LocalPort $Port -Action Allow | Out-Null
        Write-Host "  Nebula UDP (Port $Port): 許可" -ForegroundColor Green

        # プログラム許可
        New-NetFirewallRule -DisplayName "Nebula Program In" -Direction Inbound -Program $Nebula -Action Allow | Out-Null
        New-NetFirewallRule -DisplayName "Nebula Program Out" -Direction Outbound -Program $Nebula -Action Allow | Out-Null
        Write-Host "  Nebula Program: 許可" -ForegroundColor Green
    }
}

# サービスインストール
if ($Install) {
    Write-Host ""
    Write-Host "Windows サービスをインストールしています..."

    if (-not (Test-Administrator)) {
        Write-Error "サービスのインストールには管理者権限が必要です。管理者として再実行してください。"
        exit 1
    }

    # NSSM の存在確認
    if (-not (Test-Path $NssmPath)) {
        Write-Error @"
nssm.exe が見つかりません: $NssmPath

以下の手順で NSSM を取得してください:
1. https://nssm.cc/download から nssm.exe をダウンロード
2. $FlatnetBase\ に nssm.exe を配置
"@
        exit 1
    }

    # 既存サービスの確認と削除
    $existingService = Get-Service -Name "Nebula" -ErrorAction SilentlyContinue
    if ($existingService) {
        Write-Host "  既存のサービスを停止・削除しています..."
        Stop-Service -Name "Nebula" -Force -ErrorAction SilentlyContinue
        & $NssmPath remove Nebula confirm
    }

    # サービス登録
    Write-Host "  サービスを登録しています..."
    & $NssmPath install Nebula $Nebula 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "NSSM install に失敗しました (exit code: $LASTEXITCODE)"
    }

    & $NssmPath set Nebula AppDirectory "$FlatnetBase\nebula" 2>&1 | Out-Null
    & $NssmPath set Nebula AppParameters "-config $ConfigFile" 2>&1 | Out-Null
    & $NssmPath set Nebula Description "Flatnet Nebula ($HostName)" 2>&1 | Out-Null
    & $NssmPath set Nebula Start SERVICE_AUTO_START 2>&1 | Out-Null

    # ログ設定
    & $NssmPath set Nebula AppStdout "$LogsDir\nebula.log" 2>&1 | Out-Null
    & $NssmPath set Nebula AppStderr "$LogsDir\nebula.log" 2>&1 | Out-Null
    & $NssmPath set Nebula AppRotateFiles 1 2>&1 | Out-Null
    & $NssmPath set Nebula AppRotateBytes 10485760 2>&1 | Out-Null

    Write-Host "  サービス登録: 完了" -ForegroundColor Green

    if ($Start) {
        Write-Host ""
        Write-Host "サービスを開始しています..."
        Start-Service -Name "Nebula"
        Start-Sleep -Seconds 2

        $service = Get-Service -Name "Nebula"
        if ($service.Status -eq "Running") {
            Write-Host "  サービス状態: Running" -ForegroundColor Green
        } else {
            Write-Warning "  サービス状態: $($service.Status)"
            Write-Host "  ログを確認してください: $LogsDir\nebula.log"
        }
    }
}

# ルーティング設定
if ($SetupRouting) {
    Write-Host ""
    Write-Host "ルーティングを設定しています..."
    $routingScript = "$FlatnetBase\scripts\setup-routing.ps1"
    if (Test-Path $routingScript) {
        & $routingScript -FlatnetBase $FlatnetBase
    } else {
        Write-Warning "ルーティングスクリプトが見つかりません: $routingScript"
        Write-Host "  手動で .\setup-routing.ps1 を実行してください"
    }
}

# 結果サマリー
Write-Host ""
Write-Host "===============================" -ForegroundColor Cyan
Write-Host "セットアップ完了" -ForegroundColor Green
Write-Host "===============================" -ForegroundColor Cyan
Write-Host ""
Write-Host "設定:" -ForegroundColor Yellow
Write-Host "  Host Name: $HostName"
Write-Host "  Lighthouse: $LighthouseAddr ($LighthouseIp)"
Write-Host "  Listen Port: $Port"
Write-Host "  Config: $ConfigFile"
Write-Host "  Logs: $LogsDir\nebula.log"
Write-Host ""

if (-not $Install) {
    Write-Host "次のステップ:" -ForegroundColor Cyan
    Write-Host "  1. テスト起動: & `"$Nebula`" -config `"$ConfigFile`""
    Write-Host "  2. サービス登録: .\setup-host.ps1 -HostName $HostName -LighthouseAddr `"$LighthouseAddr`" -Install -Start -SetupFirewall"
    Write-Host ""
}

# 確認コマンド
Write-Host "確認コマンド:" -ForegroundColor Yellow
Write-Host "  ポート確認: netstat -an | findstr $Port"
Write-Host "  サービス確認: Get-Service Nebula"
Write-Host "  ログ確認: Get-Content $LogsDir\nebula.log -Tail 20"
Write-Host "  Lighthouse への ping: ping $LighthouseIp"
