# Flatnet Nebula Lighthouse Setup Script
# Phase 3 - Stage 1
#
# Usage: .\setup-lighthouse.ps1 [-Port 4242] [-Install] [-Start]
#
# Prerequisites:
#   - nebula.exe が F:\flatnet\nebula\ に配置されていること
#   - CA 証明書と Lighthouse 証明書が生成済み
#   - 管理者権限で実行 (-Install オプション使用時)

[CmdletBinding()]
param(
    [int]$Port = 4242,
    [switch]$Install,
    [switch]$Start,
    [switch]$SetupFirewall,
    [string]$FlatnetBase = "F:\flatnet"
)

$ErrorActionPreference = "Stop"

# パス設定
$Nebula = "$FlatnetBase\nebula\nebula.exe"
$NssmPath = "$FlatnetBase\nssm.exe"
$ConfigNebulaDir = "$FlatnetBase\config\nebula"
$LogsDir = "$FlatnetBase\logs"
$ConfigFile = "$ConfigNebulaDir\config.yaml"

$CaCrt = "$ConfigNebulaDir\ca.crt"
$LighthouseCrt = "$ConfigNebulaDir\lighthouse.crt"
$LighthouseKey = "$ConfigNebulaDir\lighthouse.key"

Write-Host "Flatnet Nebula Lighthouse Setup" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""

# nebula.exe の存在確認
if (-not (Test-Path $Nebula)) {
    Write-Error @"
nebula.exe が見つかりません: $Nebula

以下の手順で Nebula バイナリを取得してください:
1. https://github.com/slackhq/nebula/releases から nebula-windows-amd64.zip をダウンロード
2. 展開して nebula.exe と nebula-cert.exe を $FlatnetBase\nebula\ に配置
"@
    exit 1
}

# 証明書の存在確認
$missingFiles = @()
if (-not (Test-Path $CaCrt)) { $missingFiles += "CA 証明書: $CaCrt" }
if (-not (Test-Path $LighthouseCrt)) { $missingFiles += "Lighthouse 証明書: $LighthouseCrt" }
if (-not (Test-Path $LighthouseKey)) { $missingFiles += "Lighthouse 秘密鍵: $LighthouseKey" }

if ($missingFiles.Count -gt 0) {
    Write-Error @"
必要なファイルが見つかりません:
$($missingFiles -join "`n")

以下のコマンドで証明書を生成してください:
  .\gen-ca.ps1
  .\gen-host-cert.ps1 -Name lighthouse -Ip 10.100.0.1/16
"@
    exit 1
}

# logs ディレクトリ作成
if (-not (Test-Path $LogsDir)) {
    New-Item -ItemType Directory -Path $LogsDir -Force | Out-Null
}

# 設定ファイルの生成
Write-Host "設定ファイルを生成しています..."

# パス区切りをスラッシュに変換（YAML 用）
$FlatnetBaseYaml = $FlatnetBase -replace '\\', '/'

$configContent = @"
# Flatnet Nebula Lighthouse Configuration
# Generated by setup-lighthouse.ps1 at $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

pki:
  ca: $FlatnetBaseYaml/config/nebula/ca.crt
  cert: $FlatnetBaseYaml/config/nebula/lighthouse.crt
  key: $FlatnetBaseYaml/config/nebula/lighthouse.key

lighthouse:
  am_lighthouse: true

listen:
  host: 0.0.0.0
  port: $Port

logging:
  level: info
  format: text

tun:
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false

firewall:
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: icmp
      host: any
    - port: any
      proto: any
      group: any
"@

Set-Content -Path $ConfigFile -Value $configContent -Encoding UTF8
Write-Host "  設定ファイル: $ConfigFile" -ForegroundColor Green

# 設定テスト
Write-Host ""
Write-Host "設定をテストしています..."
& $Nebula -config $ConfigFile -test
if ($LASTEXITCODE -ne 0) {
    Write-Error "設定テストに失敗しました"
    exit 1
}
Write-Host "  設定テスト: 成功" -ForegroundColor Green

# ファイアウォール設定
if ($SetupFirewall) {
    Write-Host ""
    Write-Host "ファイアウォールを設定しています..."

    # 管理者権限チェック
    $isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $isAdmin) {
        Write-Warning "ファイアウォール設定には管理者権限が必要です。管理者として再実行してください。"
    } else {
        # 既存ルールを削除
        $existingRules = Get-NetFirewallRule -DisplayName "Nebula*" -ErrorAction SilentlyContinue
        if ($existingRules) {
            $existingRules | Remove-NetFirewallRule -ErrorAction SilentlyContinue
        }

        # UDP ポート開放
        New-NetFirewallRule -DisplayName "Nebula UDP" -Direction Inbound -Protocol UDP -LocalPort $Port -Action Allow | Out-Null
        Write-Host "  Nebula UDP (Port $Port): 許可" -ForegroundColor Green

        # プログラム許可
        New-NetFirewallRule -DisplayName "Nebula Program In" -Direction Inbound -Program $Nebula -Action Allow | Out-Null
        New-NetFirewallRule -DisplayName "Nebula Program Out" -Direction Outbound -Program $Nebula -Action Allow | Out-Null
        Write-Host "  Nebula Program: 許可" -ForegroundColor Green
    }
}

# サービスインストール
if ($Install) {
    Write-Host ""
    Write-Host "Windows サービスをインストールしています..."

    # 管理者権限チェック
    $isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    if (-not $isAdmin) {
        Write-Error "サービスのインストールには管理者権限が必要です。管理者として再実行してください。"
        exit 1
    }

    # NSSM の存在確認
    if (-not (Test-Path $NssmPath)) {
        Write-Error @"
nssm.exe が見つかりません: $NssmPath

以下の手順で NSSM を取得してください:
1. https://nssm.cc/download から nssm.exe をダウンロード
2. $FlatnetBase\ に nssm.exe を配置
"@
        exit 1
    }

    # 既存サービスの確認と削除
    $existingService = Get-Service -Name "Nebula" -ErrorAction SilentlyContinue
    if ($existingService) {
        Write-Host "  既存のサービスを停止・削除しています..."
        Stop-Service -Name "Nebula" -Force -ErrorAction SilentlyContinue
        & $NssmPath remove Nebula confirm
    }

    # サービス登録
    Write-Host "  サービスを登録しています..."
    & $NssmPath install Nebula $Nebula 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "NSSM install に失敗しました (exit code: $LASTEXITCODE)"
    }

    & $NssmPath set Nebula AppDirectory "$FlatnetBase\nebula" 2>&1 | Out-Null
    & $NssmPath set Nebula AppParameters "-config $ConfigFile" 2>&1 | Out-Null
    & $NssmPath set Nebula Description "Flatnet Nebula (Lighthouse)" 2>&1 | Out-Null
    & $NssmPath set Nebula Start SERVICE_AUTO_START 2>&1 | Out-Null

    # ログ設定
    & $NssmPath set Nebula AppStdout "$LogsDir\nebula.log" 2>&1 | Out-Null
    & $NssmPath set Nebula AppStderr "$LogsDir\nebula.log" 2>&1 | Out-Null
    & $NssmPath set Nebula AppRotateFiles 1 2>&1 | Out-Null
    & $NssmPath set Nebula AppRotateBytes 10485760 2>&1 | Out-Null

    Write-Host "  サービス登録: 完了" -ForegroundColor Green

    if ($Start) {
        Write-Host ""
        Write-Host "サービスを開始しています..."
        Start-Service -Name "Nebula"
        Start-Sleep -Seconds 2

        $service = Get-Service -Name "Nebula"
        if ($service.Status -eq "Running") {
            Write-Host "  サービス状態: Running" -ForegroundColor Green
        } else {
            Write-Warning "  サービス状態: $($service.Status)"
            Write-Host "  ログを確認してください: $LogsDir\nebula.log"
        }
    }
}

# 結果サマリー
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "セットアップ完了" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "設定:" -ForegroundColor Yellow
Write-Host "  Lighthouse IP: 10.100.0.1/16"
Write-Host "  Listen Port: $Port"
Write-Host "  Config: $ConfigFile"
Write-Host "  Logs: $LogsDir\nebula.log"
Write-Host ""

if (-not $Install) {
    Write-Host "次のステップ:" -ForegroundColor Cyan
    Write-Host "  1. テスト起動: & `"$Nebula`" -config `"$ConfigFile`""
    Write-Host "  2. サービス登録: .\setup-lighthouse.ps1 -Install -Start -SetupFirewall"
    Write-Host ""
}

# ポート確認コマンド
Write-Host "確認コマンド:" -ForegroundColor Yellow
Write-Host "  ポート確認: netstat -an | findstr $Port"
Write-Host "  サービス確認: Get-Service Nebula"
Write-Host "  ログ確認: Get-Content $LogsDir\nebula.log -Tail 20"
