# Flatnet Monitoring Stack
# Phase 4, Stage 1-2: Monitoring and Logging Infrastructure
#
# Components:
# - Prometheus: Metrics collection and alerting rules
# - Grafana: Visualization dashboards
# - Alertmanager: Alert routing and notification
# - Node Exporter: Host system metrics
# - Loki: Log aggregation
# - Promtail: Log shipping
#
# Usage:
#   podman-compose up -d
#   podman-compose logs -f
#   podman-compose down

version: "3.8"

services:
  # Prometheus - Metrics collection
  prometheus:
    image: docker.io/prom/prometheus:v2.48.1
    container_name: flatnet-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts:/etc/prometheus/alerts:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/-/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - monitoring

  # Grafana - Visualization
  # NOTE: Change GF_SECURITY_ADMIN_PASSWORD for production use!
  grafana:
    image: docker.io/grafana/grafana:10.2.3
    container_name: flatnet-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      # SECURITY: Change this password for production deployments
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-flatnet}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - monitoring

  # Alertmanager - Alert routing
  alertmanager:
    image: docker.io/prom/alertmanager:v0.26.0
    container_name: flatnet-alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9093/-/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - monitoring

  # Node Exporter - Host metrics
  node-exporter:
    image: docker.io/prom/node-exporter:v1.7.0
    container_name: flatnet-node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9100/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - monitoring

  # Loki - Log aggregation
  loki:
    image: docker.io/grafana/loki:2.9.3
    container_name: flatnet-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ../logging/loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki_data:/loki
    command:
      - "-config.file=/etc/loki/loki-config.yml"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - monitoring

  # Promtail - Log shipping agent
  promtail:
    image: docker.io/grafana/promtail:2.9.3
    container_name: flatnet-promtail
    restart: unless-stopped
    ports:
      - "9080:9080"
    volumes:
      - ../logging/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      # Gateway logs (Windows via WSL2 mount)
      - /mnt/f/flatnet/logs:/mnt/f/flatnet/logs:ro
      # CNI Plugin logs
      - /var/log/flatnet:/var/log/flatnet:ro
      # Container logs (Podman storage)
      - /var/lib/containers/storage/overlay-containers:/var/lib/containers/storage/overlay-containers:ro
      # Positions file persistence (dedicated directory for clarity)
      - promtail_positions:/var/promtail
    command:
      - "-config.file=/etc/promtail/promtail-config.yml"
    depends_on:
      loki:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9080/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  alertmanager_data:
    driver: local
  loki_data:
    driver: local
  promtail_positions:
    driver: local
